#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export DISPLAY=1  # fix ls++ sizes

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# if [ -e /Users/christophermcdevitt/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/christophermcdevitt/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
