#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


export PERL_LOCAL_LIB_ROOT="/Users/chris/perl5:$PERL_LOCAL_LIB_ROOT";
export PERL_MB_OPT="--install_base "/Users/chris/perl5"";
export PERL_MM_OPT="INSTALL_BASE=/Users/chris/perl5";
export PERL5LIB="/Users/chris/perl5/lib/perl5:$PERL5LIB";
export PATH="/Users/chris/perl5/bin:$PATH";

export DISPLAY=1  # fix ls++ sizes
